@ECHO OFF

ECHO You fool. We're doomed!

TIMEOUT /T 3

ECHO Aaaaaaa!

TIMEOUT /T 2

ECHO AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!!11!!!1

TIMEOUT /T 4
