@ECHO OFF

ECHO You fool. We're doomed!

TIMEOUT /T 3

@ECHO OFF

ECHO Aaaaaaa!

TIMEOUT /T 2

@echo off
set loopcount=100
:loop
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
set /a loopcount=loopcount-1
if %loopcount%==0 goto exitloop
goto loop
:exitloop

ECHO AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!!11!!1!!!

TIMEOUT /T 4
